### ISSUE TITLE
codestyle is broken + javadoc is missing

### ISSUE THREAD

**Issue by ghost** [arty-shock/java_project#2]
1. magic number
- move "/1a2b3c" and others to constants or enums
2. idea analyze
- run from IDEA: Analyze / Inspect Code
- fix all
3. checkstyle
- install https://plugins.jetbrains.com/plugin/1065-checkstyle-idea into IDEA
- run checkstyle with SunChecks
- fix all issues except LineLenghtCheck (120 characters is allowed)

**Comment by arty-shock** [comment]
all the steps done
